#!/usr/bin/env bash
# This script displays information about the domain passed as an argument.

get_dns_info() {
    subdomain=$2
    # List of all available subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")
    # Extract the subdomain from the list if provided
    if [ "$subdomain" ]; then
        subdomains=("$subdomain")
    fi
    # Generate the dns audit info
    for sub in "${subdomains[@]}"; do
        dig +noall +answer "$sub.$1" |
        awk -v _sub="$sub" '{print "The subdomain " _sub " is a " $4 " record and points to " $5}'
    done
}

get_dns_info "$1" "$2"
