#!/usr/bin/env bash
# This script makse sure that Nginx is running, and listening on port 80 of all the server’s active IPv4 IPs
sed -i "s/listen 8080 default_server/listen 80 default_server/" "/etc/nginx/sites-enabled/default"
service nginx restart
pkill -o nginx
