#!/usr/bin/env bash
# This script makse sure that Nginx is running, and listening on port 80 of all the server’s active IPv4 IPs
sed -i -r "s/listen ([0-9]+) default_server/listen 80 default_server/" "/etc/nginx/sites-available/default";
service nginx restart
service nginx stop;
