#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.

n=0
echo $$ > var/run/myscript.pid
trap "echo Y U no love me?!; rm -f /var/run/myscript.pid; exit" SIGINT
trap "echo I hate the kill command; rm -f /var/run/myscript.pid; exit" SIGTERM

while [ $n -le 1 ]
do
    echo "To infinity and beyond"
done
